markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "with_toc_data", "superscript", "smart"]
pygments: true
title: Ramboll UK Graduate Design Project 2014
permalink: /blog/:title.html
